/* Generated By:JJTree: Do not edit this line. ASTBooleanTrue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTBooleanTrue extends SimpleNode {
  public ASTBooleanTrue(int id) {
    super(id);
  }

  public ASTBooleanTrue(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5e0aeb342336cbc8515c10b4b963e9e (do not edit this line) */
