/* Generated By:JJTree: Do not edit this line. ASTBooleanExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTBooleanExpression extends SimpleNode {
  public ASTBooleanExpression(int id) {
    super(id);
  }

  public ASTBooleanExpression(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0476a1f6eb9f7ba1ddd36efad98187d (do not edit this line) */
