/* Generated By:JJTree: Do not edit this line. ASTBooleanFalse.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTBooleanFalse extends SimpleNode {
  public ASTBooleanFalse(int id) {
    super(id);
  }

  public ASTBooleanFalse(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6ccb3ea7788b070b0d6a8c578f434da (do not edit this line) */
