/* Generated By:JJTree: Do not edit this line. ASTClassBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTClassBody extends SimpleNode {
  public ASTClassBody(int id) {
    super(id);
  }

  public ASTClassBody(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ef365974851f28d86dbd159fa5834f5 (do not edit this line) */
