/* Generated By:JJTree: Do not edit this line. ASTDecrement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTDecrement extends SimpleNode {
  public ASTDecrement(int id) {
    super(id);
  }

  public ASTDecrement(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4c72596408c44d6ec74f857db739f88 (do not edit this line) */
