/* Generated By:JJTree: Do not edit this line. ASTElseStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTElseStatement extends SimpleNode {
  public ASTElseStatement(int id) {
    super(id);
  }

  public ASTElseStatement(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a66765127e0a5fbf7b56d269acd06085 (do not edit this line) */
