/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f77c293e69c230b0727247db767fbec (do not edit this line) */
