/* Generated By:JJTree: Do not edit this line. ASTFunctionBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTFunctionBody extends SimpleNode {
  public ASTFunctionBody(int id) {
    super(id);
  }

  public ASTFunctionBody(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17662de2b4efe830435d6322942874b6 (do not edit this line) */
