/* Generated By:JJTree: Do not edit this line. ASTIncrement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTIncrement extends SimpleNode {
  public ASTIncrement(int id) {
    super(id);
  }

  public ASTIncrement(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f21fc19eb284a2da08450f7ebd649c46 (do not edit this line) */
