/* Generated By:JJTree: Do not edit this line. ASTMultiply.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTMultiply extends SimpleNode {
  public ASTMultiply(int id) {
    super(id);
  }

  public ASTMultiply(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c7ff0672767e33be4385780f662b968 (do not edit this line) */
