/* Generated By:JJTree: Do not edit this line. ASTNumberLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTNumberLiteral extends SimpleNode {
  public ASTNumberLiteral(int id) {
    super(id);
  }

  public ASTNumberLiteral(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43d331fc45411f5c9340b1e67d671c19 (do not edit this line) */
