/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b284d46358f08b3215129d0afe258e8 (do not edit this line) */
