/* Generated By:JJTree: Do not edit this line. ASTType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=199ab55994e557eb13332cc02326ff70 (do not edit this line) */
