/* Generated By:JJTree: Do not edit this line. ASTVarAssignment.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ast;

public
class ASTVarAssignment extends SimpleNode {
  public ASTVarAssignment(int id) {
    super(id);
  }

  public ASTVarAssignment(MyJavaParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e695e7f5a84b9df24c56ec78b22d155e (do not edit this line) */
