/* Generated By:JavaCC: Do not edit this line. MyJavaParserTreeConstants.java Version 7.0.13 */
package ast;

public interface MyJavaParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTFUNCTIONDECLARATION = 2;
  public int JJTPARAMETERS = 3;
  public int JJTFUNCTIONBODY = 4;
  public int JJTTYPE = 5;
  public int JJTVOID = 6;
  public int JJTVARDECLARATION = 7;
  public int JJTVARASSIGNMENT = 8;
  public int JJTRETURNSTATEMENT = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTIFSTATEMENT = 11;
  public int JJTELSESTATEMENT = 12;
  public int JJTWHILESTATEMENT = 13;
  public int JJTFORSTATEMENT = 14;
  public int JJTFORINIT = 15;
  public int JJTUPDATEEXPRESSION = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTINCREMENT = 18;
  public int JJTDECREMENT = 19;
  public int JJTASSIGNMENTEXPRESSION = 20;
  public int JJTBOOLEANEXPRESSION = 21;
  public int JJTCONDITIONALEXPRESSION = 22;
  public int JJTRELATIONALEXPRESSION = 23;
  public int JJTADDITIVEEXPRESSION = 24;
  public int JJTADD = 25;
  public int JJTSUBTRACT = 26;
  public int JJTTERM = 27;
  public int JJTMULTIPLY = 28;
  public int JJTDIVIDE = 29;
  public int JJTFACTOR = 30;
  public int JJTNUMBERLITERAL = 31;
  public int JJTSTRINGLITERAL = 32;
  public int JJTBOOLEANTRUE = 33;
  public int JJTBOOLEANFALSE = 34;
  public int JJTCLASSBODY = 35;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "FunctionDeclaration",
    "Parameters",
    "FunctionBody",
    "Type",
    "void",
    "VarDeclaration",
    "VarAssignment",
    "ReturnStatement",
    "Assignment",
    "IfStatement",
    "ElseStatement",
    "WhileStatement",
    "ForStatement",
    "ForInit",
    "UpdateExpression",
    "Identifier",
    "Increment",
    "Decrement",
    "AssignmentExpression",
    "BooleanExpression",
    "ConditionalExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "Add",
    "Subtract",
    "Term",
    "Multiply",
    "Divide",
    "Factor",
    "NumberLiteral",
    "StringLiteral",
    "BooleanTrue",
    "BooleanFalse",
    "ClassBody",
  };
}
/* JavaCC - OriginalChecksum=d41744248d2fea952bae7ac34be73e48 (do not edit this line) */
